# Generated by Django 3.0.5 on 2020-05-05 07:03

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, unique=True)),
                ('text', ckeditor_uploader.fields.RichTextUploadingField()),
                ('createDateTime', models.DateTimeField(auto_now=True, verbose_name='createTime')),
                ('updateDateTime', models.DateTimeField(auto_now_add=True, verbose_name='updateTime')),
            ],
        ),
    ]
