# Generated by Django 3.0.5 on 2020-05-27 12:17

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineLearn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('detail', ckeditor_uploader.fields.RichTextUploadingField()),
                ('price', models.TextField()),
                ('teacher', models.TextField()),
                ('time', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
