# Generated by Django 3.0.5 on 2020-06-13 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_sell'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellOnline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('nameOfmyClass', models.EmailField(max_length=254)),
                ('rahgiri', models.CharField(max_length=16)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
