# Generated by Django 3.0.5 on 2020-06-13 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20200613_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellonline',
            name='rahgiri',
        ),
    ]
