# Generated by Django 3.0.5 on 2020-06-13 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_sellonline_rahgiri'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='fileZip/'),
        ),
    ]
