# Generated by Django 3.0.5 on 2020-06-17 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20200618_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='pub_date',
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sellonline',
            name='pub_date',
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
    ]
