# Generated by Django 3.0.5 on 2020-06-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20200618_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='nameOfmyClass',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sellonline',
            name='nameOfmyClass',
            field=models.CharField(max_length=100),
        ),
    ]
